#!/usr/bin/env python3
"""account-weekly-review — Friday digest of the week's account activity.

Summarises new delivered work, open/overdue actions, upcoming KPI deadlines and
gaps for a customer (Clancy), emails Pete, and stamps the review time so the
Cockpit can show 'last reviewed'. Default computes + prints; pass --send to email.

Cron: Fridays 17:00 (com.peterashcroft.account-weekly-review), --send.
"""
# CRON-META
# what: Friday digest of the week's Clancy account activity, emailed to Pete
# why: Weekly Clancy review (delivered, overdue, waiting-on-Clancy, KPI deadlines) without manual prep
# reads: CC account_* store
# writes: email to Pete + account_state.last_weekly_review
# entity: customers
# report:
# schedule: 0 17 * * 5
# timezone: Atlantic/Canary
# CRON-META-END
import os
import sys
import json
import datetime
import urllib.request

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import account_store as store

_VAULT = os.environ.get("VAULT", "/Users/peterashcroft/Second Brain")
C = "clancy"
# bootstrap runs the script bare on Railway (no args) → send by default; --dry/--no-send suppress.
SEND = not any(a in sys.argv for a in ("--dry", "--dry-run", "--no-send"))
RESEND_KEY_FILE = os.path.join(_VAULT, "Library/processes/secrets/command-centre-resend-key.json")
TO = "pete.ashcroft@sygma-solutions.com"


def send_email(subject, html):
    k = json.load(open(RESEND_KEY_FILE))
    key = k.get("api_key") or k.get("key") or k.get("resend_api_key") or list(k.values())[0]
    body = {"from": "Command Centre <commandcentre@sygma-solutions.com>", "to": [TO], "subject": subject, "html": html}
    req = urllib.request.Request("https://api.resend.com/emails", data=json.dumps(body).encode(),
                                 headers={"Authorization": "Bearer " + key, "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.status


def main():
    today = datetime.date.today()
    wk_ago = (today - datetime.timedelta(days=7)).isoformat()
    deliv = store.select("account_deliverables", f"customer=eq.{C}&select=date,title,charge,created_at,workstream&order=date.desc")
    acts = store.select("account_actions", f"customer=eq.{C}&select=title,due,status,owner_side")
    kpis = store.select("account_obligations", f"customer=eq.{C}&type=eq.kpi&select=label,deadline,status")

    new_deliv = [d for d in deliv if (d.get("created_at") or "")[:10] >= wk_ago or (d.get("date") or "") >= wk_ago]
    overdue = [a for a in acts if a.get("due") and a["due"] < today.isoformat()]
    waiting_clancy = [a for a in acts if a.get("owner_side") == "clancy"]
    upcoming = sorted([o for o in kpis if o.get("deadline")], key=lambda o: o["deadline"])[:4]

    def ul(items):
        return "<ul>" + "".join(f"<li>{x}</li>" for x in items) + "</ul>" if items else "<p style='color:#888'>None.</p>"

    html = f"""<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:640px">
<h2 style="color:#d97706">Clancy weekly review</h2>
<p style="color:#555">Week to {today.strftime('%d %b %Y')}. Live record: <a href="https://commandcentre.info/m/clancy-cockpit">Cockpit</a> · <a href="https://commandcentre.info/m/clancy-delivery-log">Delivery log</a>.</p>
<h3>Delivered this week ({len(new_deliv)})</h3>{ul([d['title'] for d in new_deliv])}
<h3>Overdue actions ({len(overdue)})</h3>{ul([f"{a['title']} (due {a.get('due')})" for a in overdue])}
<h3>Waiting on Clancy ({len(waiting_clancy)})</h3>{ul([a['title'] for a in waiting_clancy])}
<h3>Next KPI deadlines</h3>{ul([f"{o['label']} ({o.get('deadline')})" for o in upcoming])}
<p style="color:#888;font-size:12px">Totals: {len(deliv)} delivered · {len(acts)} open actions. Generated by account-weekly-review.</p>
</div>"""

    status = "not sent"
    if SEND:
        subj = "Clancy weekly review " + today.strftime("%d %b %Y")
        status = f"sent HTTP {send_email(subj, html)}"
    store.set_state(C, "last_weekly_review", datetime.datetime.now(datetime.timezone.utc).isoformat())
    print(f"account-weekly-review {C}: delivered_this_week={len(new_deliv)} overdue={len(overdue)} "
          f"waiting_clancy={len(waiting_clancy)} kpis={len(upcoming)} | email {status}")
    store.daily_note_line(f"account-weekly-review: {len(new_deliv)} delivered this week, {len(overdue)} overdue, {len(waiting_clancy)} waiting on Clancy | email {status}")
    store.refresh_state_of_play(C)


if __name__ == "__main__":
    main()
