#!/usr/bin/env python3
"""
ads-snapshot.py -- regenerate the Sygma Google Ads account-state vault doc.

Single source of truth for what's live in Sygma's Google Ads. Pulls the
account structure (campaigns, ad groups, keywords, ads, negatives, bidding,
conversion actions, 30d metrics, top search terms) via ads-api.py and writes:

  Properties/Sygma Solutions Website/data/google-ads-account.md     (human-readable)
  Properties/Sygma Solutions Website/data/google-ads-account.json   (raw state)

The markdown preserves the manual changes ledger + decisions sections via
<!-- AUTOGEN:START -->...<!-- AUTOGEN:END --> markers. Anything outside the
markers is human-edited, anything inside gets overwritten on each run.

Re-runnable safely. Driven by ads-api.py (config: google-ads-api-configuration).

Usage:
  python3 ads-snapshot.py            # write
  python3 ads-snapshot.py --check    # dry-run; print summary, don't write
"""

import datetime
import importlib.util
import json
import os
import re
import sys

ROOT = "/tmp/pbs"
DOC_PATH = f"{ROOT}/Properties/Sygma Solutions Website/data/google-ads-account.md"
JSON_PATH = f"{ROOT}/Properties/Sygma Solutions Website/data/google-ads-account.json"

AUTOGEN_START = "<!-- AUTOGEN:START -- regenerated by ads-snapshot.py, edits inside this block will be overwritten -->"
AUTOGEN_END = "<!-- AUTOGEN:END -->"

# ---- load ads-api helper ----
_spec = importlib.util.spec_from_file_location(
    "ads_api", os.path.join(os.path.dirname(os.path.abspath(__file__)), "ads-api.py")
)
ads_api_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ads_api_mod)


def micros(m):
    """Format micros as £x.xx."""
    return f"£{int(m or 0) / 1e6:.2f}"


def pull_state():
    """Pull every relevant slice of the account into a single dict."""
    ads = ads_api_mod.GoogleAdsAPI()
    out = {
        "snapshot_iso": datetime.datetime.now(
            datetime.timezone.utc
        ).isoformat(timespec="seconds"),
        "customer_id": ads.default_customer_id,
        "login_customer_id": ads.login_customer_id,
    }

    # Customer info
    cust = ads.query(
        "SELECT customer.id, customer.descriptive_name, customer.currency_code, "
        "customer.time_zone, customer.tracking_url_template "
        "FROM customer"
    )
    out["customer"] = cust[0]["customer"] if cust else {}

    # Campaigns (live only)
    out["campaigns"] = []
    for r in ads.query(
        "SELECT campaign.id, campaign.name, campaign.status, "
        "campaign.advertising_channel_type, campaign.bidding_strategy_type, "
        "campaign.maximize_conversions.target_cpa_micros, "
        "campaign_budget.amount_micros, campaign_budget.delivery_method "
        "FROM campaign WHERE campaign.status != 'REMOVED' "
        "ORDER BY campaign.name"
    ):
        c = r["campaign"]
        b = r.get("campaignBudget", {})
        out["campaigns"].append({
            "id": c.get("id"),
            "name": c.get("name"),
            "status": c.get("status"),
            "channel": c.get("advertisingChannelType"),
            "bidding": c.get("biddingStrategyType"),
            "target_cpa_micros": (c.get("maximizeConversions") or {}).get("targetCpaMicros"),
            "budget_micros": b.get("amountMicros"),
            "budget_delivery": b.get("deliveryMethod"),
        })

    # Ad groups (live campaigns only)
    out["ad_groups"] = []
    for r in ads.query(
        "SELECT ad_group.id, ad_group.name, ad_group.status, ad_group.type, "
        "ad_group.cpc_bid_micros, campaign.id, campaign.name "
        "FROM ad_group "
        "WHERE campaign.status != 'REMOVED' AND ad_group.status != 'REMOVED' "
        "ORDER BY campaign.name, ad_group.name"
    ):
        ag = r["adGroup"]
        c = r["campaign"]
        out["ad_groups"].append({
            "id": ag.get("id"),
            "name": ag.get("name"),
            "status": ag.get("status"),
            "type": ag.get("type"),
            "cpc_bid_micros": ag.get("cpcBidMicros"),
            "campaign_id": c.get("id"),
            "campaign_name": c.get("name"),
        })

    # Keywords (live ad groups only)
    out["keywords"] = []
    for r in ads.query(
        "SELECT ad_group_criterion.criterion_id, ad_group_criterion.keyword.text, "
        "ad_group_criterion.keyword.match_type, ad_group_criterion.status, "
        "ad_group_criterion.quality_info.quality_score, ad_group_criterion.cpc_bid_micros, "
        "ad_group.id, ad_group.name "
        "FROM ad_group_criterion "
        "WHERE ad_group_criterion.type = 'KEYWORD' "
        "AND ad_group_criterion.status != 'REMOVED' "
        "AND ad_group.status != 'REMOVED' "
        "AND campaign.status != 'REMOVED'"
    ):
        crit = r["adGroupCriterion"]
        ag = r["adGroup"]
        out["keywords"].append({
            "criterion_id": crit.get("criterionId"),
            "ad_group_id": ag.get("id"),
            "ad_group_name": ag.get("name"),
            "text": (crit.get("keyword") or {}).get("text"),
            "match_type": (crit.get("keyword") or {}).get("matchType"),
            "status": crit.get("status"),
            "quality_score": (crit.get("qualityInfo") or {}).get("qualityScore"),
            "cpc_bid_micros": crit.get("cpcBidMicros"),
        })

    # Ads (live ad groups only)
    out["ads"] = []
    for r in ads.query(
        "SELECT ad_group_ad.ad.id, ad_group_ad.ad.type, ad_group_ad.status, "
        "ad_group_ad.ad.responsive_search_ad.headlines, "
        "ad_group_ad.ad.responsive_search_ad.descriptions, "
        "ad_group_ad.ad.final_urls, "
        "ad_group.id, ad_group.name "
        "FROM ad_group_ad "
        "WHERE ad_group_ad.status != 'REMOVED' "
        "AND ad_group.status != 'REMOVED' "
        "AND campaign.status != 'REMOVED'"
    ):
        ad = r["adGroupAd"]["ad"]
        rsa = ad.get("responsiveSearchAd") or {}
        out["ads"].append({
            "id": ad.get("id"),
            "type": ad.get("type"),
            "status": r["adGroupAd"].get("status"),
            "ad_group_id": r["adGroup"].get("id"),
            "ad_group_name": r["adGroup"].get("name"),
            "headlines": [h.get("text") for h in (rsa.get("headlines") or [])],
            "descriptions": [d.get("text") for d in (rsa.get("descriptions") or [])],
            "final_urls": ad.get("finalUrls", []),
        })

    # Shared negative lists
    out["shared_sets"] = []
    for r in ads.query(
        "SELECT shared_set.id, shared_set.name, shared_set.type, shared_set.status, "
        "shared_set.member_count "
        "FROM shared_set WHERE shared_set.status != 'REMOVED'"
    ):
        s = r["sharedSet"]
        out["shared_sets"].append({
            "id": s.get("id"),
            "name": s.get("name"),
            "type": s.get("type"),
            "status": s.get("status"),
            "member_count": s.get("memberCount"),
        })

    # Shared criteria (negatives in those lists)
    out["shared_criteria"] = []
    for r in ads.query(
        "SELECT shared_set.id, shared_set.name, shared_criterion.criterion_id, "
        "shared_criterion.keyword.text, shared_criterion.keyword.match_type "
        "FROM shared_criterion WHERE shared_set.status != 'REMOVED'"
    ):
        crit = r["sharedCriterion"]
        s = r["sharedSet"]
        out["shared_criteria"].append({
            "shared_set_id": s.get("id"),
            "shared_set_name": s.get("name"),
            "criterion_id": crit.get("criterionId"),
            "text": (crit.get("keyword") or {}).get("text"),
            "match_type": (crit.get("keyword") or {}).get("matchType"),
        })

    # Campaign-level negatives
    out["campaign_negatives"] = []
    for r in ads.query(
        "SELECT campaign.id, campaign.name, campaign_criterion.criterion_id, "
        "campaign_criterion.keyword.text, campaign_criterion.keyword.match_type, "
        "campaign_criterion.type "
        "FROM campaign_criterion "
        "WHERE campaign.status != 'REMOVED' "
        "AND campaign_criterion.negative = TRUE "
        "AND campaign_criterion.type = 'KEYWORD'"
    ):
        crit = r["campaignCriterion"]
        c = r["campaign"]
        out["campaign_negatives"].append({
            "campaign_id": c.get("id"),
            "campaign_name": c.get("name"),
            "criterion_id": crit.get("criterionId"),
            "text": (crit.get("keyword") or {}).get("text"),
            "match_type": (crit.get("keyword") or {}).get("matchType"),
        })

    # Sitelinks + other extensions attached to live campaigns
    out["sitelinks"] = []
    for r in ads.query(
        "SELECT campaign.id, campaign.name, campaign.status, "
        "campaign_asset.field_type, campaign_asset.status, "
        "asset.sitelink_asset.link_text, "
        "asset.sitelink_asset.description1, "
        "asset.sitelink_asset.description2, "
        "asset.final_urls, asset.resource_name "
        "FROM campaign_asset "
        "WHERE campaign.status != 'REMOVED' "
        "AND campaign_asset.field_type = 'SITELINK' "
        "AND campaign_asset.status != 'REMOVED'"
    ):
        sa = r["asset"].get("sitelinkAsset") or {}
        out["sitelinks"].append({
            "campaign_id": r["campaign"].get("id"),
            "campaign_name": r["campaign"].get("name"),
            "asset_resource": r["asset"].get("resourceName"),
            "link_text": sa.get("linkText"),
            "description1": sa.get("description1"),
            "description2": sa.get("description2"),
            "final_url": (r["asset"].get("finalUrls") or [None])[0],
        })

    # Callout + structured snippet + other-type extension counts
    out["other_extensions"] = []
    for r in ads.query(
        "SELECT campaign.id, campaign.name, campaign.status, "
        "campaign_asset.field_type, campaign_asset.status, asset.type "
        "FROM campaign_asset "
        "WHERE campaign.status != 'REMOVED' "
        "AND campaign_asset.field_type != 'SITELINK' "
        "AND campaign_asset.status != 'REMOVED'"
    ):
        out["other_extensions"].append({
            "campaign_id": r["campaign"].get("id"),
            "field_type": r["campaignAsset"].get("fieldType"),
            "asset_type": r["asset"].get("type"),
        })

    # Account-level (customer_asset) extensions inheriting to all campaigns
    out["account_extensions"] = []
    for r in ads.query(
        "SELECT customer_asset.field_type, customer_asset.status, asset.type "
        "FROM customer_asset WHERE customer_asset.status != 'REMOVED'"
    ):
        out["account_extensions"].append({
            "field_type": r["customerAsset"].get("fieldType"),
            "asset_type": r["asset"].get("type"),
        })

    # Conversion actions (active only)
    out["conversion_actions"] = []
    for r in ads.query(
        "SELECT conversion_action.id, conversion_action.name, conversion_action.status, "
        "conversion_action.primary_for_goal, conversion_action.type, "
        "conversion_action.value_settings.default_value, conversion_action.category "
        "FROM conversion_action WHERE conversion_action.status != 'REMOVED'"
    ):
        ca = r["conversionAction"]
        out["conversion_actions"].append({
            "id": ca.get("id"),
            "name": ca.get("name"),
            "status": ca.get("status"),
            "primary_for_goal": ca.get("primaryForGoal"),
            "type": ca.get("type"),
            "category": ca.get("category"),
            "default_value": (ca.get("valueSettings") or {}).get("defaultValue"),
        })

    # 30-day metrics (top-line + per ad group + top search terms)
    metrics = {"period": "LAST_30_DAYS"}
    for r in ads.query(
        "SELECT customer.id, metrics.cost_micros, metrics.clicks, metrics.impressions, "
        "metrics.conversions FROM customer WHERE segments.date DURING LAST_30_DAYS"
    ):
        m = r["metrics"]
        metrics["top_line"] = {
            "cost_micros": m.get("costMicros"),
            "clicks": m.get("clicks"),
            "impressions": m.get("impressions"),
            "conversions": m.get("conversions"),
        }

    metrics["per_ad_group"] = []
    for r in ads.query(
        "SELECT ad_group.id, ad_group.name, metrics.cost_micros, metrics.clicks, "
        "metrics.impressions, metrics.conversions "
        "FROM ad_group WHERE segments.date DURING LAST_30_DAYS "
        "AND ad_group.status != 'REMOVED' AND campaign.status != 'REMOVED' "
        "AND metrics.impressions > 0"
    ):
        m = r["metrics"]
        ag = r["adGroup"]
        metrics["per_ad_group"].append({
            "ad_group_id": ag.get("id"),
            "ad_group_name": ag.get("name"),
            "cost_micros": m.get("costMicros"),
            "clicks": m.get("clicks"),
            "impressions": m.get("impressions"),
            "conversions": m.get("conversions"),
        })

    metrics["top_search_terms"] = []
    for r in ads.query(
        "SELECT search_term_view.search_term, metrics.cost_micros, metrics.clicks, "
        "metrics.conversions FROM search_term_view "
        "WHERE segments.date DURING LAST_30_DAYS AND metrics.clicks > 0 "
        "ORDER BY metrics.cost_micros DESC LIMIT 25"
    ):
        m = r["metrics"]
        metrics["top_search_terms"].append({
            "search_term": r["searchTermView"]["searchTerm"],
            "cost_micros": m.get("costMicros"),
            "clicks": m.get("clicks"),
            "conversions": m.get("conversions"),
        })

    out["metrics_30d"] = metrics
    return out


def render_autogen(state):
    """Render the auto-generated middle of the doc as markdown."""
    lines = []
    snap = state["snapshot_iso"]
    cust = state.get("customer") or {}
    name = cust.get("descriptiveName") or "Sygma Training — All Courses"
    lines.append(
        f"_Last synced: **{snap}** UTC by `ads-snapshot.py`._  \n"
        f"_Account: {name} ({state['customer_id']}, "
        f"{cust.get('currencyCode','?')} · {cust.get('timeZone','?')}). "
        f"MCC: {state['login_customer_id']}._"
    )
    lines.append("")

    # ---- 30d snapshot
    m = state["metrics_30d"].get("top_line", {})
    cost = int(m.get("cost_micros", 0) or 0) / 1e6
    cl = int(m.get("clicks", 0) or 0)
    impr = int(m.get("impressions", 0) or 0)
    cv = float(m.get("conversions", 0) or 0)
    lines.append("## 30-day top-line")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Spend | £{cost:.2f} |")
    lines.append(f"| Clicks | {cl} |")
    lines.append(f"| Impressions | {impr} |")
    lines.append(f"| Conversions | {cv:.1f} |")
    if impr:
        lines.append(f"| CTR | {100*cl/impr:.2f}% |")
    if cl:
        lines.append(f"| Avg CPC | £{cost/cl:.2f} |")
    if cl:
        lines.append(f"| Conv rate | {100*cv/cl:.2f}% |")
    if cv:
        lines.append(f"| CPA | £{cost/cv:.2f} |")
    lines.append("")

    # ---- Campaigns
    lines.append("## Active campaigns")
    lines.append("")
    if not state["campaigns"]:
        lines.append("_None._")
    else:
        lines.append("| ID | Name | Status | Channel | Bidding | Daily budget | Target CPA |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in state["campaigns"]:
            budget = micros(c["budget_micros"]) if c["budget_micros"] else "—"
            tcpa = micros(c["target_cpa_micros"]) if c["target_cpa_micros"] else "—"
            lines.append(
                f"| `{c['id']}` | {c['name']} | {c['status']} | "
                f"{c.get('channel','?')} | {c.get('bidding','?')} | {budget} | {tcpa} |"
            )
    lines.append("")

    # ---- Ad groups + nested keywords + ads
    lines.append("## Ad groups, keywords, ads")
    lines.append("")
    # bucket keywords + ads + 30d-metrics by ad-group
    kw_by_ag = {}
    for k in state["keywords"]:
        kw_by_ag.setdefault(k["ad_group_id"], []).append(k)
    ads_by_ag = {}
    for a in state["ads"]:
        ads_by_ag.setdefault(a["ad_group_id"], []).append(a)
    m30_by_ag = {x["ad_group_id"]: x for x in state["metrics_30d"]["per_ad_group"]}

    for ag in state["ad_groups"]:
        kws = kw_by_ag.get(ag["id"], [])
        ads = ads_by_ag.get(ag["id"], [])
        m30 = m30_by_ag.get(ag["id"], {})
        cost = int(m30.get("cost_micros", 0)) / 1e6
        cv = float(m30.get("conversions", 0))
        lines.append(
            f"### {ag['name']} (`{ag['id']}`, {ag['status']})"
        )
        lines.append(
            f"_Campaign: {ag['campaign_name']} · "
            f"30d: £{cost:.2f} / {int(m30.get('clicks',0))} clicks / "
            f"{int(m30.get('impressions',0))} impr / {cv:.1f} conv_"
        )
        lines.append("")

        # Top 15 keywords by spend (we'd need keyword-level 30d metrics to sort by spend;
        # without that, group by QS then alphabetical)
        if kws:
            kw_sorted = sorted(
                kws,
                key=lambda k: (
                    -(k.get("quality_score") or 0),
                    k.get("text") or "",
                ),
            )
            lines.append(f"**Keywords ({len(kws)} active):** showing all by QS desc")
            lines.append("")
            lines.append("| QS | Match | Status | Text | Criterion |")
            lines.append("|---|---|---|---|---|")
            for k in kw_sorted:
                qs = k.get("quality_score")
                qs_disp = str(qs) if qs is not None else "—"
                lines.append(
                    f"| {qs_disp} | {k.get('match_type','?')} | {k.get('status','?')} | "
                    f"{k.get('text','?')} | `{k.get('criterion_id','?')}` |"
                )
            lines.append("")
        else:
            lines.append("_No active keywords._")
            lines.append("")

        if ads:
            lines.append(f"**Ads ({len(ads)}):**")
            lines.append("")
            for a in ads:
                heads = " / ".join((a.get("headlines") or [])[:5])
                descs = " / ".join((a.get("descriptions") or [])[:2])
                fu = ", ".join(a.get("final_urls") or [])
                lines.append(f"- `{a['id']}` ({a.get('type','?')}, {a.get('status','?')})")
                if heads:
                    lines.append(f"  - Headlines: {heads}")
                if descs:
                    lines.append(f"  - Descriptions: {descs}")
                if fu:
                    lines.append(f"  - Final URL: {fu}")
            lines.append("")

    # ---- Shared negative lists
    lines.append("## Shared negative lists")
    lines.append("")
    if not state["shared_sets"]:
        lines.append("_None._")
    else:
        # group criteria by shared_set_id
        crit_by_set = {}
        for c in state["shared_criteria"]:
            crit_by_set.setdefault(c["shared_set_id"], []).append(c)
        for s in state["shared_sets"]:
            crit = crit_by_set.get(s["id"], [])
            lines.append(f"### {s['name']} (`{s['id']}`, {s['status']})")
            lines.append(f"_{s['type']} · {s.get('member_count','?')} members_")
            lines.append("")
            if crit:
                # group by match type
                lines.append(f"<details><summary>{len(crit)} negative keywords (click to expand)</summary>")
                lines.append("")
                lines.append("| Match | Text | Criterion |")
                lines.append("|---|---|---|")
                for c in sorted(crit, key=lambda x: (x.get("match_type", ""), x.get("text", ""))):
                    lines.append(
                        f"| {c.get('match_type','?')} | {c.get('text','?')} | "
                        f"`{c.get('criterion_id','?')}` |"
                    )
                lines.append("")
                lines.append("</details>")
            lines.append("")

    # ---- Campaign-level negatives
    if state["campaign_negatives"]:
        lines.append("## Campaign-level negatives")
        lines.append("")
        lines.append("| Campaign | Match | Text |")
        lines.append("|---|---|---|")
        for n in state["campaign_negatives"]:
            lines.append(
                f"| {n.get('campaign_name','?')} | {n.get('match_type','?')} | "
                f"{n.get('text','?')} |"
            )
        lines.append("")

    # ---- Sitelinks + other extensions
    lines.append("## Sitelinks (campaign-level)")
    lines.append("")
    if not state.get("sitelinks"):
        lines.append("_None._")
    else:
        lines.append("| Link text | URL | Description |")
        lines.append("|---|---|---|")
        for sl in state["sitelinks"]:
            url = sl.get("final_url", "?")
            d1 = sl.get("description1") or ""
            d2 = sl.get("description2") or ""
            desc = f"{d1} / {d2}" if d1 or d2 else "—"
            lines.append(f"| {sl.get('link_text','?')} | `{url}` | {desc} |")
    lines.append("")

    # Other extension types (callout, structured snippet, etc) — counts only
    from collections import Counter
    other_counts = Counter(e.get("field_type") for e in state.get("other_extensions", []))
    acct_counts = Counter(e.get("field_type") for e in state.get("account_extensions", []))
    if other_counts or acct_counts:
        lines.append("## Other extensions (counts)")
        lines.append("")
        lines.append("| Field type | Campaign-level | Account-level |")
        lines.append("|---|---|---|")
        all_types = sorted(set(other_counts) | set(acct_counts))
        for ft in all_types:
            lines.append(f"| {ft} | {other_counts.get(ft, 0)} | {acct_counts.get(ft, 0)} |")
        lines.append("")

    # ---- Conversion actions
    lines.append("## Conversion actions")
    lines.append("")
    if not state["conversion_actions"]:
        lines.append("_None._")
    else:
        lines.append("| ID | Name | Status | Primary? | Category | Default value |")
        lines.append("|---|---|---|---|---|---|")
        for ca in state["conversion_actions"]:
            lines.append(
                f"| `{ca['id']}` | {ca['name']} | {ca['status']} | "
                f"{'PRIMARY' if ca.get('primary_for_goal') else 'secondary'} | "
                f"{ca.get('category','?')} | {ca.get('default_value','—')} |"
            )
    lines.append("")

    # ---- Top search terms (30d)
    lines.append("## Top search terms (last 30 days, by spend)")
    lines.append("")
    sts = state["metrics_30d"]["top_search_terms"]
    if not sts:
        lines.append("_None._")
    else:
        lines.append("| Search term | Spend | Clicks | Conversions |")
        lines.append("|---|---|---|---|")
        for s in sts:
            lines.append(
                f"| {s['search_term']} | "
                f"{micros(s.get('cost_micros'))} | "
                f"{int(s.get('clicks',0))} | "
                f"{float(s.get('conversions',0)):.1f} |"
            )

    return "\n".join(lines)


INITIAL_DOC_TEMPLATE = """---
type: account-state
property: "[[Properties/Sygma Solutions Website]]"
updated: {today}
sync_method: ads-snapshot.py (manual + weekly cron `sygma-ads-account-snapshot`)
sync_helper: "[[Library/processes/scripts/ads-api-py|ads-api.py]]"
api_config: "[[google-ads-api-configuration]]"
mcc_id: 220-653-9186
customer_id: 173-909-0181
tags: [google-ads, sygma, account-state]
---

# Sygma Google Ads -- Account State

Single source of truth for the live Sygma Google Ads structure. Auto-refreshed weekly + on demand via `Library/processes/scripts/ads-snapshot.py`. Raw state mirror at [[google-ads-account.json]].

Manual sections (decisions, change ledger, planned restructure) are preserved across runs. The auto-generated section between the AUTOGEN markers below is overwritten each sync.

## Cross-references

- `[[Library/processes/google-ads-api-configuration]]` -- auth chain, dev token, helper script, GAQL cheatsheet
- `[[reference_sygma_google_ads_mcc]]` -- MCC + advertiser IDs, 2FA pattern
- `[[Projects/SY-Website/ads]]` -- operational ads project (campaigns, recovery plan, handover to Appear Online)
- `[[Library/processes/scripts/ads-api-py|ads-api.py]]` -- the helper script driving everything here
- `[[Library/processes/scheduled-tasks#sygma-ads-account-snapshot]]` -- the weekly sync cron

{autogen_start}
{autogen}
{autogen_end}

## Recent changes ledger

Append-only log of structural changes made manually (via UI or API). Run-detected diffs from `ads-snapshot.py` are listed too. Newest at top.

- **2026-05-19** -- Removed paused `Safe Digging & CAT2 Training` ad group (gid `194245072013`, 41 kw, 2 ads) from live campaign. Pete decision: not actively selling that line.
- **2026-05-18** -- Added `sygma` PHRASE-match negative to Sygma Master Negatives. Closes the full brand-bid leak (was £24/mo, 0 conv) by also blocking all branded amplification searches like `sygma cat and genny training`.
- **2026-05-18** -- Added `sygma` EXACT + `sygma solutions` EXACT negatives to Sygma Master Negatives (superseded by the PHRASE later same day; kept as explicit subsets).
- **2026-05-18** -- Paused brand keyword `sygma` in `Cable Avoidance & CAT Genny Training` (was QS 1, £15 paid clicks 0 conv).
- **2026-05-18** -- Google Ads API Basic Access dev token approved. Direct API supersedes Windsor.ai. Helper: `[[Library/processes/scripts/ads-api-py|ads-api.py]]`.
- **2026-05-06** -- Switched bidding strategy `TARGET_IMPRESSION_SHARE` → `MAXIMIZE_CONVERSIONS`. Pete decision: stop paying premium for top-spot impression share when CPA was £400+.
- **2026-05-06** -- Sygma Master Negatives consolidated to 205 keywords (3 prior lists merged + orphan deleted; 33 commercial-intent filters added).
- **2026-05-06** -- MCC 220-653-9186 (SYGMA) created. Advertiser 173-909-0181 linked.
- **2026-03-28** -- Daily budget increased £50 → £65. Search Partners off.

## Decisions

- **Maximize Conversions strategy, no Target CPA initially** (locked 2026-05-06) -- 14-day learning window before refining; target CPA goal ~£100 after data settles.
- **Defensive posture on `sygma` brand-bidding** (locked 2026-05-18) -- own organic #1+#2 captures all branded searches; paid pickup wasted £24/mo at 0 conv. Phrase-match negative blocks all sygma+X variants.
- **Appear Online takes over Ads from June 2026** (£300/mo). Pete owns through May. Structural restructure decisions deferred to AO unless they break something pre-handover.
- **Account hygiene cap** (2026-05-19) -- only live campaign + 2 live ad groups remain. No restructure mess to inherit.

## Planned restructure (deferred to Appear Online)

The single live ad group `Cable Avoidance & CAT Genny Training` mixes three theme clusters (HSG47 / CAT Genny / EUSR). Tighter ad-group themes would improve QS + ad relevance. But:

- The numbered restructure attempts (Campaign 1 / 2 / 3 from earlier) all got removed
- Maximize Conversions has converged on the current 2-group layout
- Restructuring 10 days before AO takes over risks confusing the handover

Recommendation: pass current state to AO with this doc as their starting reference, let them propose the next structure.
""".replace("{autogen_start}", AUTOGEN_START).replace("{autogen_end}", AUTOGEN_END)


def splice_autogen(existing, new_autogen):
    """Replace content between AUTOGEN markers; preserve everything else.
    If markers absent, append a new autogen block at the end."""
    if AUTOGEN_START in existing and AUTOGEN_END in existing:
        before = existing.split(AUTOGEN_START)[0]
        after = existing.split(AUTOGEN_END, 1)[1]
        return f"{before}{AUTOGEN_START}\n{new_autogen}\n{AUTOGEN_END}{after}"
    # Fallback: append at end
    return existing + f"\n\n{AUTOGEN_START}\n{new_autogen}\n{AUTOGEN_END}\n"


def bump_frontmatter_updated(text, today):
    """Set the YAML frontmatter `updated:` field to `today`. Operates only on the
    leading `---`..`---` block so body text starting with `updated:` is never touched.
    If frontmatter exists without an `updated:` line, one is appended to it."""
    m = re.match(r"(?s)^(---\n.*?\n)(---\n)", text)
    if not m:
        return text
    fm, close = m.group(1), m.group(2)
    if re.search(r"(?m)^updated:.*$", fm):
        fm = re.sub(r"(?m)^updated:.*$", f"updated: {today}", fm, count=1)
    else:
        fm = fm + f"updated: {today}\n"
    return fm + close + text[m.end():]


def _structural(state):
    """Normalised structural slices for change-detection. Excludes volatile
    metrics / bids / quality scores (they drift every run)."""
    if not state:
        return {}
    g = lambda k: state.get(k, []) or []
    return {
        "campaigns": sorted(
            f"{c.get('name')}|{c.get('status')}|{c.get('channel')}|{c.get('bidding')}|{c.get('budget_micros')}|{c.get('target_cpa_micros')}"
            for c in g("campaigns")),
        "ad_groups": sorted(
            f"{a.get('campaign_name')}|{a.get('name')}|{a.get('status')}|{a.get('type')}"
            for a in g("ad_groups")),
        "keywords": sorted(
            f"{k.get('ad_group_name')}|{k.get('text')}|{k.get('match_type')}|{k.get('status')}"
            for k in g("keywords")),
        "ads": sorted(
            f"{a.get('ad_group_name')}|{a.get('status')}|{','.join(a.get('final_urls') or [])}|{' / '.join(a.get('headlines') or [])}|{' / '.join(a.get('descriptions') or [])}"
            for a in g("ads")),
        "sitelinks": sorted(
            f"{s.get('campaign_name')}|{s.get('link_text')}|{s.get('final_url')}|{s.get('description1')}|{s.get('description2')}"
            for s in g("sitelinks")),
        "other_extensions": sorted(
            f"{e.get('field_type')}|{e.get('asset_type')}" for e in g("other_extensions")),
        "account_extensions": sorted(
            f"{e.get('field_type')}|{e.get('asset_type')}" for e in g("account_extensions")),
        "campaign_negatives": sorted(
            f"{n.get('campaign_name')}|{n.get('text')}|{n.get('match_type')}" for n in g("campaign_negatives")),
        "shared_criteria": sorted(
            f"{s.get('shared_set_name')}|{s.get('text')}|{s.get('match_type')}" for s in g("shared_criteria")),
        "conversion_actions": sorted(
            f"{c.get('name')}|{c.get('status')}|{c.get('primary_for_goal')}|{c.get('category')}" for c in g("conversion_actions")),
    }


def _diff_summary(prev_s, new_s):
    """Return (changed: bool, summary: str) comparing two _structural() dicts."""
    if not prev_s:
        return True, "first snapshot (no prior state to compare)"
    parts = []
    for key in new_s:
        old, new = set(prev_s.get(key, [])), set(new_s.get(key, []))
        if old == new:
            continue
        added, removed = new - old, old - new
        if key == "sitelinks":
            def _label(items):
                return ", ".join(sorted(f"{x.split('|')[1]}→{x.split('|')[2]}" for x in items)) or "—"
            bits = []
            if added:
                bits.append(f"added [{_label(added)}]")
            if removed:
                bits.append(f"removed [{_label(removed)}]")
            parts.append("sitelinks " + "; ".join(bits))
        else:
            counts = []
            if added:
                counts.append(f"+{len(added)}")
            if removed:
                counts.append(f"-{len(removed)}")
            parts.append(f"{key.replace('_', ' ')} {'/'.join(counts)}")
    if not parts:
        return False, "no structural change"
    return True, "; ".join(parts)


def main():
    dry_run = "--check" in sys.argv

    print(f"[{datetime.datetime.now().isoformat(timespec='seconds')}] Pulling state...", flush=True)
    state = pull_state()
    print(
        f"  campaigns={len(state['campaigns'])} "
        f"ad_groups={len(state['ad_groups'])} "
        f"keywords={len(state['keywords'])} "
        f"ads={len(state['ads'])} "
        f"shared_negatives={len(state['shared_criteria'])} "
        f"conversion_actions={len(state['conversion_actions'])}",
        flush=True,
    )

    # Structural change detection vs the previous snapshot (read BEFORE the
    # JSON sidecar is overwritten). Drives the daily cron's quiet-unless-changed
    # behaviour: the cron only writes a daily-note line on CHANGES_DETECTED.
    prev = None
    if os.path.exists(JSON_PATH):
        try:
            with open(JSON_PATH) as f:
                prev = json.load(f)
        except Exception:
            prev = None
    changed, change_summary = _diff_summary(_structural(prev), _structural(state))
    print(
        f"CHANGES_DETECTED: {change_summary}" if changed else "NO_STRUCTURAL_CHANGES",
        flush=True,
    )

    if dry_run:
        print("--check mode: not writing files.")
        print("SNAPSHOT_COMPLETE")
        return

    # JSON sidecar
    os.makedirs(os.path.dirname(JSON_PATH), exist_ok=True)
    with open(JSON_PATH, "w") as f:
        json.dump(state, f, indent=2, sort_keys=True)
    print(f"Wrote {JSON_PATH}")

    autogen = render_autogen(state)

    today = datetime.date.today().isoformat()
    if os.path.exists(DOC_PATH):
        with open(DOC_PATH) as f:
            existing = f.read()
        result = splice_autogen(existing, autogen)
        result = bump_frontmatter_updated(result, today)
    else:
        result = INITIAL_DOC_TEMPLATE.format(today=today, autogen=autogen)

    with open(DOC_PATH, "w") as f:
        f.write(result)
    print(f"Wrote {DOC_PATH}")

    # Command Centre: publish the live account-state snapshot (additive; vault doc above unchanged). Non-fatal.
    try:
        import importlib.util as _il, re as _re
        def _md2html(md):
            out=[]; in_tbl=False
            for ln in md.splitlines():
                if ln.startswith("|"):
                    cells=[c.strip() for c in ln.strip().strip("|").split("|")]
                    if set("".join(cells)) <= set("-: "):
                        continue
                    if not in_tbl:
                        out.append("<table style='border-collapse:collapse;width:100%;font-size:13px;margin:6px 0;background:#fff'>"); in_tbl=True
                    out.append("<tr>"+"".join(f"<td style='border:1px solid #e2e6f0;padding:5px 8px'>{c}</td>" for c in cells)+"</tr>")
                    continue
                if in_tbl:
                    out.append("</table>"); in_tbl=False
                ln=_re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", ln)
                if ln.startswith("### "): out.append(f"<h4 style='margin:12px 0 4px'>{ln[4:]}</h4>")
                elif ln.startswith("## "): out.append(f"<h3 style='margin:14px 0 4px;color:#1B2340'>{ln[3:]}</h3>")
                elif ln.startswith("# "): out.append(f"<h2 style='margin:0 0 6px'>{ln[2:]}</h2>")
                elif ln.strip()=="": out.append("")
                else: out.append(f"<p style='margin:3px 0'>{ln}</p>")
            if in_tbl: out.append("</table>")
            return "<div style='font:14px/1.5 -apple-system,Segoe UI,sans-serif;padding:16px;color:#0b1220'>"+"\n".join(out)+"</div>"
        # The account state now renders as the NATIVE dashboard /m/sygma-ads (not a
        # 135KB md→html snapshot). Refresh its data feed (data/ads.json in the CC repo)
        # from the account JSON we just wrote, via ads-cc-publish.py.
        import subprocess as _sp
        _here = os.path.dirname(os.path.abspath(__file__))
        _r = _sp.run([__import__("sys").executable, os.path.join(_here, "ads-cc-publish.py")],
                     capture_output=True, text=True, timeout=240)
        print("  CC ads dashboard:", ((_r.stdout or _r.stderr).strip().splitlines() or ["ok"])[-1])
    except Exception as _e:
        print(f"  CC PUBLISH FAILED: {_e}")
    print("SNAPSHOT_COMPLETE")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"SNAPSHOT_FAILED: {e}", file=sys.stderr)
        raise
